safe: true
title: "Basic Data Structures and Object-Oriented Design – UCSD CSE 12"
source: .
destination: _site
lsi: false
url: "https://uscd-cse12-ss24.github.io/"
:pygments: true
collections:
  lectures:
    output: true
  assignments:
    output: true
  assignments-drafts:
    output: true
theme: jekyll-theme-midnight